# Generated by Django 4.2.1 on 2023-10-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_alter_post_content_alter_post_title_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
