# Generated by Django 4.2.6 on 2023-10-23 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_text_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
